=== le-bao-tu/XML/BTVN/Orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
   
    <xs:element name="Name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="10"></xs:minLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Producer">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="TRUBG QUOC"></xs:enumeration>
                <xs:enumeration value="MALAYSIA"></xs:enumeration>
                <xs:enumeration value="VIET NAM"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="date" type="xs:date"></xs:element>

    

    <xs:element name="Price">
       <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:positiveInteger">
                    <xs:attribute name="unit" fixed="VND" use="required"></xs:attribute>  
                </xs:extension>
            </xs:simpleContent>
       </xs:complexType>
    </xs:element>

    <xs:element name="Computer">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Name"></xs:element>
                <xs:element ref="Producer"></xs:element>
                <xs:element ref="date"></xs:element>
                <xs:element ref="Price"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Computers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Computer" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== le-bao-tu/XML/BTVN/testOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<Computers
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Orders.xsd">
    
    <Computer id="B8985">
        <Name>Lap top DELL Vostro</Name>
        <Producer>TRUBG QUOC</Producer>
        <date>2002-12-12</date>
        <Price unit="VND">124</Price>
    </Computer>
    <Computer id="B8986">
        <Name>Lap top DELL Vostro</Name>
        <Producer>VIET NAM</Producer>
        <date>2002-12-12</date>
        <Price unit="VND">124</Price>
    </Computer>
</Computers>
