=== le-bao-tu/XML/DA/Products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
    <xs:element name="id" type="xs:ID"></xs:element>
    
   <xs:element name="Name">
       <xs:simpleType>
           <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z0-9\s]{3,50}"></xs:pattern>
           </xs:restriction>
       </xs:simpleType>
   </xs:element>

   
   
   <xs:element name="Category_id">
     <xs:simpleType>
         <xs:restriction base="xs:positiveInteger">
                <xs:pattern value="[1-9]"></xs:pattern>
         </xs:restriction>
     </xs:simpleType>
   </xs:element>


   
   <xs:element name="Description">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z\s]{0,128}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
   </xs:element>

   <xs:element name="Amount">
       <xs:simpleType>
           <xs:restriction base="xs:integer">
               <xs:minExclusive value="-1"></xs:minExclusive>
              <xs:maxExclusive value="10000"></xs:maxExclusive>
           </xs:restriction>
       </xs:simpleType>
   </xs:element>

   <xs:element name="date" type="xs:dateTime"></xs:element> 

  
       <xs:simpleType name="price">
           <xs:restriction base="xs:positiveInteger">
            <xs:minExclusive value="99"></xs:minExclusive>
            <xs:maxExclusive value="10000000"></xs:maxExclusive>
           </xs:restriction>
       </xs:simpleType>
 
       <xs:element name="Price">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="price">
                    <xs:attribute name="unit" fixed="VND" use="required"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

   <xs:element name="Size">
       <xs:simpleType>
           <xs:restriction base="xs:string">
               <xs:enumeration value="M"></xs:enumeration>
               <xs:enumeration value="L"></xs:enumeration>
               <xs:enumeration value="XL"></xs:enumeration>
               <xs:enumeration value="XXL"></xs:enumeration>
           </xs:restriction>
       </xs:simpleType>
   </xs:element>


   <xs:simpleType name="image">
        <xs:restriction base="xs:string">
            <xs:enumeration value=".JPG"></xs:enumeration>
            <xs:enumeration value=".PNG"></xs:enumeration>
        </xs:restriction>
   </xs:simpleType>
   
 
       <xs:element name="Image">
        <xs:complexType>
          <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="image_format" type="image"  use="required"></xs:attribute>
              </xs:extension>
          </xs:simpleContent>
        
        </xs:complexType>
    </xs:element>

    

   <xs:element name="Sanpham">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="id"></xs:element>
               <xs:element ref="Name"></xs:element>
               <xs:element ref="Category_id"></xs:element>
               <xs:element ref="Description"></xs:element>
               <xs:element ref="Amount"></xs:element>
               <xs:element ref="date"></xs:element>
               <xs:element ref="Price"></xs:element>
               <xs:element ref="Size"></xs:element>
                <xs:element ref="Image"></xs:element>
           </xs:sequence>
       </xs:complexType>
   </xs:element>

   <xs:element name="DSSanpham">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="Sanpham" minOccurs="0" maxOccurs="unbounded"></xs:element>
           </xs:sequence>
       </xs:complexType>
   </xs:element>
</xs:schema>

=== le-bao-tu/XML/DA/TestProduct.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Products.css" type="text/css"?>
<!-- <?xml-stylesheet href="Products.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="Products_sort.xsl" type="text/xsl"?> -->
<?xml-stylesheet href="Price_Size.xsl" type="text/xsl"?>
<!-- <?xml-stylesheet href="Show_shirt.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="Background.xsl" type="text/xsl"?>  -->


<DSSanpham xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Products.xsd">
    <Sanpham>
        <id>B8985</id>
        <Name>AO SO MI</Name>
        <Category_id>1</Category_id>
        <Description>san pham chat luong</Description>
        <Amount>9999</Amount>
        <date>2002-05-30T09:00:00</date>
        <Price unit="VND">100000</Price>
        <Size>L</Size>
        <Image image_format=".JPG">1</Image>
    </Sanpham>
    <Sanpham>
        <id>B8986</id>
        <Name>AO DA CA SAU</Name>
        <Category_id>2</Category_id>
        <Description>san pham chat luong</Description>
        <Amount>5000</Amount>
        <date>2002-05-30T09:30:00</date>
        <Price unit="VND">400000</Price>
        <Size>XXL</Size>
        <Image image_format=".PNG">2</Image>
    </Sanpham>
    <Sanpham>
        <id>B8987</id>
        <Name>QUAN BO GUCCI</Name>
        <Category_id>3</Category_id>
        <Description>san pham chat luong</Description>
        <Amount>9999</Amount>
        <date>2002-05-30T09:00:00</date>
        <Price unit="VND">3000</Price>
        <Size>XL</Size>
        <Image image_format=".JPG">3</Image>
    </Sanpham>

    <Sanpham>
        <id>B8988</id>
        <Name>QUAN BO LV</Name>
        <Category_id>4</Category_id>
        <Description>san pham chat luong</Description>
        <Amount>0</Amount>
        <date>2002-05-30T09:00:00</date>
        <Price unit="VND">7000</Price>
        <Size>M</Size>
        <Image image_format=".PNG">4</Image>
    </Sanpham>

</DSSanpham>
